# Generated by Django 3.2.8 on 2021-11-14 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 11, 14, 19, 46, 38, 32586))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 11, 14, 19, 46, 38, 32586))),
            ],
        ),
    ]
